DTC_INCLUDE += $(srctree)/../sm6475-modules/qcom/opensource/camera-kernel

dtbo-y += \
	parrot-somc-elbe-camera.dtbo \
	parrot-somc-elbe-camera-sensor-qrd.dtbo

always-y := $(dtb-y) $(dtbo-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
