DTC_INCLUDE += $(srctree)/../sm6475-modules/qcom/opensource/audio-kernel/include

dtbo-y += \
	parrot-somc-elbe-audio.dtbo \
	parrot-somc-elbe-audio-qrd-wcn6755.dtbo

always-y := $(dtb-y) $(dtbo-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
