DTC_INCLUDE += $(srctree)/../sm6475-modules/qcom/opensource/audio-kernel/include

dtbo-y += \
	elbe-audio.dtbo \
	../../qcom/audio/parrot-audio.dtbo \
	../../qcom/audio/parrot-audio-qrd-wcn6755.dtbo

targets += ../../qcom/audio/elbe-audio.dtbo
always-y := $(dtb-y) $(dtbo-y) ../../qcom/audio/elbe-audio.dtbo
subdir-y := $(dts-dirs)

quiet_cmd_copy_dtbo = COPY    $@
cmd_copy_dtbo = mkdir -p $(dir $@) && cp -f $< $@

$(obj)/../../qcom/audio/elbe-audio.dtbo: $(obj)/elbe-audio.dtbo FORCE
	$(call if_changed,copy_dtbo)

clean-files := *.dtb *.dtbo